### ISSUE TITLE
License slightly updated

### ISSUE THREAD

**Issue by mizuumi** [shunk031/huggingface-datasets_JDocQA#3]
Thank you for creating the huggingface dataset for JDocQA! Of course we welcome any derivations from JDocQA!

We slightly update our term: `JDocQA dataset annotations are distributed under CC BY-SA 4.0. We are delighted to see many derivations from JDocQA! When you create any derivations, e.g., datasets, papers, etc, from JDocQA, please cite our paper accordingly. If your derivations are web-based projects, please cite our paper and include the link to this github page.`
Can you update the license of JDocQA in this repo following this?

**Comment by shunk031** [comment]
Of course! Thank you for letting me know. I'll update the license at PR #4.

**Comment by shunk031** [comment]
Hi @mizuumi, PR #4 has been merged into the main branch. Please reopen this issue if anything is missing.
